FROM apache/nifi:2.6.0

USER root

RUN cd /opt/nifi/nifi-current/lib/ && \
    curl -LO https://repo1.maven.org/maven2/org/apache/nifi/nifi-hadoop-libraries-nar/2.6.0/nifi-hadoop-libraries-nar-2.6.0.nar && \
    curl -LO https://repo1.maven.org/maven2/org/apache/nifi/nifi-hadoop-nar/2.6.0/nifi-hadoop-nar-2.6.0.nar

RUN chown nifi:nifi /opt/nifi/nifi-current/lib/nifi-hadoop*.nar

USER nifi