FROM apache/airflow:2.10.0

USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends default-jre-headless \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow
RUN pip install --no-cache-dir "apache-airflow-providers-apache-spark<5.0.0" pyspark==3.5.3